version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: payment_platform_db
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:8.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass cachepass
    volumes:
      - cachedata:/data
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmqlib:/var/lib/rabbitmq
      - rabbitmqlog:/var/log/rabbitmq
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheusdata:/prometheus
    ports:
      - "9090:9090"
    restart: always
  grafana:
    image: grafana/grafana-enterprise
    restart: always
    ports:
      - '3000:3000'  
    volumes:
      - grafanadata:/var/lib/grafana
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    restart: always
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_URI: postgres:5432/postgres?sslmode=disable
      DATA_SOURCE_USER: postgres 
      DATA_SOURCE_PASS: postgres
    depends_on: [postgres]
configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."       
volumes:
  pgdata:
  cachedata:
  rabbitmqlib:
  rabbitmqlog: 
  prometheusdata:
  grafanadata: