{
 "title": "Prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Redis Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=\"redis-exporter:9121\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RabbitMQ Queued Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(queue) (rabbitmq_queue_messages_ready{instance=\"rabbitmq:15692\", job=\"rabbitmq\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "rabbitmq_queue_messages{instance=\"rabbitmq:15692\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres TPS by DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_database_xact_commit{instance=~\"postgres-exporter:9187\"}[5m]) \r\n                 + rate(pg_stat_database_xact_rollback{instance=~\"postgres-exporter:9187\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up Services",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(up) by (job)", "legendFormat": "__auto" }
   ]
  }
 ]
}